routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');
Route::group(['middleware' => ['guest:web'], 'prefix' => 'admin',], function () {

    Route::get('connexion', 'AuthenticationController@adminLogin')->name('login');
    Route::post('connexion', 'AuthenticationController@adminAuthentication')->name('admins.authentication');
});

Route::group(['middleware' => ['auth:web'], 'prefix' => 'admin',], function () {
    Route::get('/', function () {
        return redirect()->route('dashboard');
    });
    Route::get('/tableau_de_bord', 'DashboardController@index')->name('dashboard');
    Route::resource('parishioners', 'ParishionerController');
    Route::resource('supervisors', 'SupervisorController');
    Route::resource('masses', 'MassController');
    Route::resource('causes', 'CauseController');
    Route::resource('admins', 'AdminController');
    Route::resource('dioceses', 'DioceseController');
    Route::resource('parishes', 'ParishController');
    Route::resource('transactions', 'TransactionController');
    Route::resource('request-types', 'RequestTypeController');
    Route::delete('request-types/delete/{request_type}', 'RequestTypeController@destroy')->name('request-types.delete');
    Route::resource('countries', 'CountryController');
    Route::resource('cities', 'CityController');
    Route::resource('parishioners-request', 'MassRequestController');
});
Route::get('deconnexion', 'AuthenticationController@logout')->name('logout');

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $dates = ['name_field'];
    protected $fillable = ['name', 'country_id'];

    public function country()
    {
        return $this->belongsTo(Country::class);
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CityValidateRequest;
use App\Models\City;
use App\Models\Country;
use Illuminate\Http\Request;

class CityController extends Controller
{
    public function index()
    {
        $cities = City::all();
        $countries = Country::all();

        return view('admin.pages.cities.index', compact('cities', 'countries'));
    }

    public function edit($id)
    {
        try {
            $city = City::find($id);
            $countries = Country::all();
        } catch (\Exception $e) {
            dump($e->getMessage());
            die();
        }

        return view('admin.pages.cities.edit', compact('city', 'countries'));
    }

    public function store(CityValidateRequest $request)
    {
        $data = $request->validated();

        try {
            City::create($data);
        } catch (\Exception $e) {
            dump($e->getMessage());
            die();
        }
        return redirect()->route('cities.index');
    }

    public function update(CityValidateRequest $request, $id)
    {
        $data = $request->validated();

        try {
            $city = City::find($id);
            $city->update($data);
        } catch (\Exception $e) {
            dump($e->getMessage());
            die();
        }
        return redirect()->route('cities.index');
    }

    public function destroy($id)
    {
        try {
            $city = City::find($id);
            $city->delete();
        } catch (\Exception $e) {
            dump($e->getMessage());
            die();
        }

        return redirect()->back();
    }
}

resources/views/admin/pages/cities/edit.blade.php
@extends('admin.template')

@section('content')
    <div class="container-fluid">
        <div class="animated fadeIn col-md-10 offset-md-1">
            <div class="card">
                <div class="card-header">
                    <a href="#" class="text-warning">
                        <strong> {{__('Modification')}}</strong>
                    </a>
                </div>
                <form action="{{ route('cities.update', ['city' => $city->id]) }}" method="post">
                    @csrf
                    @method('patch')
                    <div class="modal-body">
                        <div class="form-group">
                            <label>{{__('Pays')}}
                            </label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-edit"></i></span>
                                </div>
                                <select name="country_id" id="country_id" class="form-control">
                                    <option value="">----{{ __('Choisir le pays') }}----</option>
                                    @foreach($countries as $country)
                                        <option value="{{ $country->id }}" {{ $country->id == $city->country_id ? 'selected' : '' }}>{{ $country->name }}</option>
                                    @endforeach
                                </select>
                                @error('country_id')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label>{{__('Nom')}}
                            </label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-edit"></i></span>
                                </div>
                                <input value="{{ $city->name }}" type="text" name="name" class="form-control" placeholder="{{__('Nom')}}">
                            </div>
                            @error('name')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="{{ route('cities.index') }}" class="btn btn-dark">Annuler</a>
                        <button class="btn btn-warning">Modifier</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/cities/index.blade.php
@extends('admin.template')
@section('content')

    <div class="container-fluid">

        <div class="animated fadeIn">
            <div class="card">
                <div class="card-header">
                    <button type="button" class="btn btn-primary rounded" data-toggle="modal" data-target="#largeModal">
                        <i class="fa fa-plus-circle"></i>
                        <strong>{{__('Ville')}}</strong>
                    </button>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-bordered datatable">
                        <thead>
                        <tr>
                            <th>Pays</th>
                            <th>Ville</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($cities as $key => $city)
                            <tr>
                                <td>{{ $city->country->name }}</td>
                                <td>{{ $city->name }}</td>
                                <td class="right">
                                    <a href="{{ route('cities.edit', ['city' => $city->id]) }}" class="btn btn-warning">
                                        <i class="fa fa-edit "></i>
                                    </a>
                                    <button type="submit" class="btn btn-danger" data-toggle="modal"
                                            data-target="#smallModal-{{ $key }}">
                                        <i class="fa fa-trash-o "></i>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="largeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-md modal-dialog modal-info" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Création d'une ville</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form action="{{ route('cities.store') }}" method="post">
                    @csrf
                    @method('post')
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="country_id">{{__('Pays')}}</label>
                            <select name="country_id" id="country_id" class="form-control">
                                <option value="">----{{ __('Choisir le pays de la ville') }}----</option>
                                @foreach($countries as $country)
                                    <option value="{{ $country->id }}">{{ $country->name }}</option>
                                @endforeach
                            </select>
                            @error('country_id')
                            <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="name">{{__('Nom')}}</label>
                            <div class="input-group">
                                <input required type="text" id="name" name="name" class="form-control"
                                       placeholder="{{__('Nom')}}">
                            </div>
                            @error('name')
                            <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="reset" class="btn btn-dark" data-dismiss="modal">Annuler</button>
                        <button type="submit" class="btn btn-success">Créer</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    @foreach($cities as $key => $city)
        <div class="modal fade" id="smallModal-{{ $key }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true">
            <div class="modal-dialog modal-sm modal-danger" role="document">
                <form action="{{ route('cities.destroy', ['city' => $city->id]) }}" method="post">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Supprimer {{ $city->name }}</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <strong>Cette action est irréversible, ête-vous sûr ?</strong>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-dark" data-dismiss="modal">Annuler</button>
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger">Oui, supprimer</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    @endforeach
    <!-- /.conainer-fluid -->
@stop