routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');
Route::group(['middleware' => ['guest:web'], 'prefix' => 'admin',], function () {

    Route::get('connexion', 'AuthenticationController@adminLogin')->name('login');
    Route::post('connexion', 'AuthenticationController@adminAuthentication')->name('admins.authentication');
});

Route::group(['middleware' => ['auth:web'], 'prefix' => 'admin',], function () {
    Route::get('/', function () {
        return redirect()->route('dashboard');
    });
    Route::get('/tableau_de_bord', 'DashboardController@index')->name('dashboard');
    Route::resource('parishioners', 'ParishionerController');
    Route::resource('supervisors', 'SupervisorController');
    Route::resource('masses', 'MassController');
    Route::resource('causes', 'CauseController');
    Route::resource('admins', 'AdminController');
    Route::resource('dioceses', 'DioceseController');
    Route::resource('parishes', 'ParishController');
    Route::resource('transactions', 'TransactionController');
    Route::resource('request-types', 'RequestTypeController');
    Route::delete('request-types/delete/{request_type}', 'RequestTypeController@destroy')->name('request-types.delete');
    Route::resource('countries', 'CountryController');
    Route::resource('cities', 'CityController');
    Route::resource('parishioners-request', 'MassRequestController');
});
Route::get('deconnexion', 'AuthenticationController@logout')->name('logout');

resources/views/admin/partials/breadcrumb.blade.php
<!-- Breadcrumb -->
<ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item"><a href="#">Admin</a></li>
    <li class="breadcrumb-item active">Dashboard</li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <a class="btn" href="#"><i class="icon-speech"></i></a>
            <a class="btn" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
            <a class="btn" href="#"><i class="icon-settings"></i> &nbsp;Settings</a>
        </div>
    </li>
</ol>

resources/views/admin/partials/footer.blade.php
<footer class="app-footer">
    <span><a href="http://coreui.io/pro/">CoreUI Pro</a> © 2017 creativeLabs.</span>
    <span class="ml-auto">Powered by <a href="http://coreui.io/pro/">CoreUI Pro</a></span>
</footer>

resources/views/admin/partials/header.blade.php
<header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand font-weight-bold" href="{{route('home')}}">D2messe</a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="nav navbar-nav d-md-down-none mr-auto">

        <li class="nav-item px-3">
            <a class="nav-link" href="{{route('dashboard')}}">{{__('Tableau de bord')}}</a>
        </li>
        <li class="nav-item px-3">
            <a class="nav-link" href="{{route('parishioners-request.index')}}">{{__('Demandes de messe')}}</a>
        </li>
        <li class="nav-item px-3">
            <a class="nav-link" href="{{route('parishioners.index')}}">{{__('Paroissiens')}}</a>
        </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
        <a href="{{route('logout')}}" class="navbar-toggler" title="{{__('Deconnexion')}}">
            <i class="icon-power font-weight-bold"></i>
        </a>
    </ul>
</header>

resources/views/admin/partials/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{{route('dashboard')}}">
                    <i class="icon-speedometer"></i> {{__('Tableau de bord')}}
                </a>
            </li>
            <li class="nav-title">
                {{__('Paroissiens')}}
            </li>
            <li class="nav-item">
                <a href="{{route('parishioners.index')}}" class="nav-link">
                    <i class="icon-people"></i> {{__('Paroissiens')}}</a>
            </li>

            <li class="nav-item">
                <a href="{{route('parishioners-request.index')}}" class="nav-link">
                    <i class="icon-layers"></i> {{__('Demandes de messe')}}
                </a>
            </li>
            <li class="nav-title">
                {{__('Paroisses')}}
            </li>
            <li class="nav-item">
                <a href="{{route('supervisors.index')}}" class="nav-link"><i class="icon-user"></i> {{__('Superviseurs')}}</a>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link" href="{{route('masses.index')}}"><i class="icon-bell"></i> {{__('Messes')}}</a>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link" href="{{route('causes.index')}}"><i class="icon-badge"></i> {{__('Causes')}}</a>
            </li>
            <li class="nav-title">
                {{__('Transactions')}}
            </li>
            <li class="nav-item">
                <a href="{{route('transactions.index')}}" class="nav-link">
                    <i class="icon-directions"></i> {{__('Transactions')}}</a>
            </li>
            <li class="nav-title">
                {{__('Paramètres')}}
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link" href="{{route('admins.index')}}">
                    <i class="icon-shield"></i> {{__('Administrateurs')}}</a>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link" href="{{route('request-types.index')}}">
                    <i class="icon-list"></i> {{__('Types de demande')}}
                </a>
            </li>
            <li class="nav-item nav-dropdown">

                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="icon-bell"></i> {{__('Églises')}}
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link" href="{{route('dioceses.index')}}">
                            <i class="icon-anchor"></i> {{__('Diocèses')}}
                        </a>
                    </li>

                    <li class="nav-item nav-dropdown">
                        <a class="nav-link" href="{{route('parishes.index')}}">
                            <i class="icon-home"></i> {{__('Paroisses')}}
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="icon-map"></i> {{__('Lieux')}}
                </a>
                <ul class="nav-dropdown-items">

                    <li class="nav-item">
                        <a href="{{route('countries.index')}}" class="nav-link">
                            <i class="icon-globe"></i> {{__('Pays')}}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('cities.index')}}" class="nav-link">
                            <i class="icon-location-pin"></i> {{__('Villes')}}</a>
                    </li>

                </ul>
            </li>

            <li class="nav-item fixed-bottom">
                <a class="nav-link" href="{{route('logout')}}">
                    <i class="icon-power"></i> {{__('Deconnexion')}}
                </a>
            </li>
        </ul>
    </nav>
    {{--<button class="sidebar-minimizer brand-minimizer" type="button"></button>--}}
</div>